/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dockassist;

/**
 *
 * @author jamesmurphy
 */
public class DockAssistGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DockAssistGUI.class.getName());
    
    private RecordList recordList; //used to store the records
    private MyStack recentStack; //MyStack object that stores recently viewed records
    private MyPriorityQueue issueQueue; //MyPriorityQueue object that stores the urgent issues

    public DockAssistGUI() {
        initComponents();
        //initialise
        recordList = new RecordList(); //creates the RecordList object
        recentStack = new MyStack(); //creates the MyStack object
        issueQueue = new MyPriorityQueue();//creates the MyPriorityQueue object
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        recordFormPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idTf = new javax.swing.JTextField();
        titleTf = new javax.swing.JTextField();
        locationTf = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descriptionTa = new javax.swing.JTextArea();
        addRecordBtn = new javax.swing.JButton();
        listRecordsBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordsTa = new javax.swing.JTextArea();
        removeRecordBtn = new javax.swing.JButton();
        searchRecordBtn = new javax.swing.JButton();
        viewRecentBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        issueFormPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        issueIdTf = new javax.swing.JTextField();
        issueTitleTf = new javax.swing.JTextField();
        issueTypeTf = new javax.swing.JTextField();
        priorityTf = new javax.swing.JTextField();
        statusTf = new javax.swing.JTextField();
        reportDateTf = new javax.swing.JTextField();
        addIssueBtn = new javax.swing.JButton();
        nextIssueBtn = new javax.swing.JButton();
        listIssuesBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        issuesTa = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DockAssistGUI");

        recordFormPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Accessibility Record"));

        jLabel1.setText("ID:");

        jLabel2.setText("Title:");

        jLabel3.setText("Description:");

        jLabel4.setText("Location:");

        descriptionTa.setColumns(20);
        descriptionTa.setRows(5);
        jScrollPane2.setViewportView(descriptionTa);

        javax.swing.GroupLayout recordFormPanelLayout = new javax.swing.GroupLayout(recordFormPanel);
        recordFormPanel.setLayout(recordFormPanelLayout);
        recordFormPanelLayout.setHorizontalGroup(
            recordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordFormPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(87, 87, 87)
                        .addComponent(idTf, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE))
                    .addGroup(recordFormPanelLayout.createSequentialGroup()
                        .addGroup(recordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(recordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titleTf)
                            .addComponent(jScrollPane2)
                            .addComponent(locationTf))))
                .addContainerGap())
        );
        recordFormPanelLayout.setVerticalGroup(
            recordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(recordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titleTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(recordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(recordFormPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(recordFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(locationTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        addRecordBtn.setText("Add Record");
        addRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecordBtnActionPerformed(evt);
            }
        });

        listRecordsBtn.setText("List Records");
        listRecordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listRecordsBtnActionPerformed(evt);
            }
        });

        recordsTa.setColumns(20);
        recordsTa.setRows(5);
        jScrollPane1.setViewportView(recordsTa);

        removeRecordBtn.setText("Delete Record");
        removeRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeRecordBtnActionPerformed(evt);
            }
        });

        searchRecordBtn.setText("Search Record");
        searchRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchRecordBtnActionPerformed(evt);
            }
        });

        viewRecentBtn.setText("View Recent");
        viewRecentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(addRecordBtn)
                        .addGap(18, 18, 18)
                        .addComponent(listRecordsBtn)
                        .addGap(18, 18, 18)
                        .addComponent(removeRecordBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchRecordBtn)
                        .addGap(18, 18, 18)
                        .addComponent(viewRecentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addComponent(recordFormPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recordFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addRecordBtn)
                    .addComponent(listRecordsBtn)
                    .addComponent(removeRecordBtn)
                    .addComponent(searchRecordBtn)
                    .addComponent(viewRecentBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Records", jPanel1);

        issueFormPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Manage Accessibility Issues"));

        jLabel5.setText("ID:");

        jLabel6.setText("Title:");

        jLabel7.setText("Issue Type:");

        jLabel8.setText("Priority:");

        jLabel9.setText("Status:");

        jLabel10.setText("Report Date:");

        issueIdTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueIdTfActionPerformed(evt);
            }
        });

        issueTitleTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueTitleTfActionPerformed(evt);
            }
        });

        statusTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTfActionPerformed(evt);
            }
        });

        addIssueBtn.setText("Add Issue");
        addIssueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIssueBtnActionPerformed(evt);
            }
        });

        nextIssueBtn.setText("Next Issue");
        nextIssueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextIssueBtnActionPerformed(evt);
            }
        });

        listIssuesBtn.setText("List Issue");
        listIssuesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listIssuesBtnActionPerformed(evt);
            }
        });

        issuesTa.setColumns(20);
        issuesTa.setRows(5);
        jScrollPane3.setViewportView(issuesTa);

        javax.swing.GroupLayout issueFormPanelLayout = new javax.swing.GroupLayout(issueFormPanel);
        issueFormPanel.setLayout(issueFormPanelLayout);
        issueFormPanelLayout.setHorizontalGroup(
            issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, issueFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, issueFormPanelLayout.createSequentialGroup()
                        .addGroup(issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(24, 24, 24)
                        .addGroup(issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(statusTf)
                            .addComponent(priorityTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issueTypeTf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(issueTitleTf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                            .addComponent(issueIdTf, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, issueFormPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(issueFormPanelLayout.createSequentialGroup()
                                .addComponent(addIssueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(nextIssueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(listIssuesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(reportDateTf))))
                .addContainerGap())
        );
        issueFormPanelLayout.setVerticalGroup(
            issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(issueFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(issueFormPanelLayout.createSequentialGroup()
                        .addGroup(issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(issueIdTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(issueTitleTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(issueTypeTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(priorityTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(statusTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(reportDateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(issueFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addIssueBtn)
                    .addComponent(nextIssueBtn)
                    .addComponent(listIssuesBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(issueFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(issueFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manage Issues", jPanel2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void statusTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusTfActionPerformed

    private void addRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecordBtnActionPerformed
        //declare variables
        int id;
        String title;
        String description;
        String location;
        //object variable that stores a new record
        DocklandsRecord record;

        //initialise variables
        id = Integer.parseInt(idTf.getText()); // gets ID valuesrting value from text field then parsed into an integer
        title = titleTf.getText(); //gets title from text field, then stored in title
        description = descriptionTa.getText(); //gets text from text field, then stored in description
        location = locationTf.getText(); // gets the text from text field, then stored in location

        //create objects
        record = new DocklandsRecord(id, title, description, location);//new Docklands object
        recordList.addRecord(record);//this adds the record to the RecordList

        recordsTa.setText("Record added successfully.\n"); // sets the text in output, text area

        idTf.setText("");//resets the ID text field
        titleTf.setText("");//resets title text field
        descriptionTa.setText("");//resets the description text area
        locationTf.setText("");//resets the location text field       

    }//GEN-LAST:event_addRecordBtnActionPerformed

    private void listRecordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listRecordsBtnActionPerformed
        recordsTa.setText(recordList.printRecords()); //displays all stored records

    }//GEN-LAST:event_listRecordsBtnActionPerformed

    private void removeRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeRecordBtnActionPerformed
        int id;//stores the record id that will be removed
        DocklandsRecord record;//stores the record to be removed
        
        if (idTf.getText().equals("")) {
            recordsTa.setText("Enter a valid ID to delete");
            return;
        }
        try {
            id = Integer.parseInt(idTf.getText()); // reads the ID from the text field
            record = recordList.searchById(id); // checks if a record with that ID exists

            if (record != null) {
                recordList.removeById(id); //removes the record
                recordsTa.setText("Record removed successfully"); //message for text area
            } else {
                recordsTa.setText("No record found with that ID"); //validation message in text area
            }
        } catch (NumberFormatException e) {//handles an invalid input for num
            recordsTa.setText("Please enter a valid number for ID");//validation message for text area
        }

    }//GEN-LAST:event_removeRecordBtnActionPerformed

    private void searchRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchRecordBtnActionPerformed
        int id;//stores the id to search
        DocklandsRecord record; //stores the returned record

        if (idTf.getText().equals("")) {
            recordsTa.setText("Please enter an ID to search");//validation for empty fields
        }
        try {//try catch used to convert text to an integer for validation
            id = Integer.parseInt(idTf.getText()); // reads id from the ID text field
            record = recordList.searchById(id); //searches for the record by using ID

            if (record != null) {
                recordsTa.setText(record.getSummary());//displays the record summary
                recentStack.push(record);//pushes the viewed record on to the stack
            } else {
                recordsTa.setText("No record found at that ID");//error message
            }
        } catch (NumberFormatException e) {//handles invalid num input
            recordsTa.setText("Please enter a valid number for ID");//displayed in text area
        }
    }//GEN-LAST:event_searchRecordBtnActionPerformed

    private void addIssueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIssueBtnActionPerformed
        //variables
        int id;
        String title;
        String description;
        String location;
        int priority;
        String status;//stores the issue status
        String issueType;//stores the issue type
        String reportDate;//stores the report date
        AccessIssue issue;//object for AccessIssue
        
        if (issueIdTf.getText().equals("") || issueTitleTf.getText().equals("") || issueTypeTf.getText().equals("") || priorityTf.getText().equals("") || statusTf.getText().equals("") || reportDateTf.getText().equals("")) {
            issuesTa.setText("Please fill in all fields");
            return;
        }
        try {//trys to convert ID and Priority into integers
            
            id = Integer.parseInt(issueIdTf.getText());//reads the ID and converts to integer
            title = issueTitleTf.getText();
            issueType = issueTypeTf.getText();
            priority = Integer.parseInt(priorityTf.getText());
            status = statusTf.getText();
            reportDate = reportDateTf.getText();
            
            description = "";
            location = "";
            //creates issue object
            issue = new AccessIssue(id, title, description, location, priority, status, issueType, reportDate);
            
            issueQueue.enqueue(priority, issue);
            issuesTa.setText("The issue was added successfully.\n");

            //reset fields after adding
            issueIdTf.setText("");
            issueTitleTf.setText("");
            issueTypeTf.setText("");
            priorityTf.setText("");
            statusTf.setText("");
            reportDateTf.setText("");
            
        } catch (NumberFormatException e) {//error handling displays message in text area for ID and Priority fields
            issuesTa.setText("Please enter a valid number for ID and Priority");
        }

    }//GEN-LAST:event_addIssueBtnActionPerformed

    private void listIssuesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listIssuesBtnActionPerformed
        issuesTa.setText(issueQueue.printPQueue());
    }//GEN-LAST:event_listIssuesBtnActionPerformed

    private void nextIssueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextIssueBtnActionPerformed
        Object nextIssue; //stores the next issue

        nextIssue = issueQueue.dequeue(); //renmoves the highest priority issue

        if (nextIssue != null) {//if an issue exists
            issuesTa.setText(nextIssue.toString());//then display it
        } else {//else
            issuesTa.setText("No issues in the queue");//send this message
        }

    }//GEN-LAST:event_nextIssueBtnActionPerformed

    private void viewRecentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecentBtnActionPerformed
        recordsTa.setText(recentStack.printStack());//print the recently viewed stack
    }//GEN-LAST:event_viewRecentBtnActionPerformed

    private void issueIdTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueIdTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueIdTfActionPerformed

    private void issueTitleTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueTitleTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_issueTitleTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DockAssistGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addIssueBtn;
    private javax.swing.JButton addRecordBtn;
    private javax.swing.JTextArea descriptionTa;
    private javax.swing.JTextField idTf;
    private javax.swing.JPanel issueFormPanel;
    private javax.swing.JTextField issueIdTf;
    private javax.swing.JTextField issueTitleTf;
    private javax.swing.JTextField issueTypeTf;
    private javax.swing.JTextArea issuesTa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton listIssuesBtn;
    private javax.swing.JButton listRecordsBtn;
    private javax.swing.JTextField locationTf;
    private javax.swing.JButton nextIssueBtn;
    private javax.swing.JTextField priorityTf;
    private javax.swing.JPanel recordFormPanel;
    private javax.swing.JTextArea recordsTa;
    private javax.swing.JButton removeRecordBtn;
    private javax.swing.JTextField reportDateTf;
    private javax.swing.JButton searchRecordBtn;
    private javax.swing.JTextField statusTf;
    private javax.swing.JTextField titleTf;
    private javax.swing.JButton viewRecentBtn;
    // End of variables declaration//GEN-END:variables
}
